{{- if .Values.check.deployment.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/owner: sditeam
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
    - name: deployment
      image: {{ .Values.check.deployment.image.repository }}:{{ .Values.check.deployment.image.tag }}
      imagePullPolicy: IfNotPresent
      env:
        - name: CHECK_DEPLOYMENT_REPLICAS
          value: "1"
        - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
          value: "true"
        {{- if .Values.check.deployment.env.CHECK_IMAGE }}
        - name: CHECK_IMAGE
          value: {{ .Values.check.deployment.env.CHECK_IMAGE }}
        {{- end }}
        {{- if .Values.check.deployment.env.CHECK_IMAGE_ROLL_TO }}
        - name: CHECK_IMAGE_ROLL_TO
          value: {{ .Values.check.deployment.env.CHECK_IMAGE_ROLL_TO }}
        {{- end }}
      resources:
        requests:
          cpu: 25m
          memory: 15Mi
        limits:
          cpu: 40m
      restartPolicy: Always
    {{- if .Values.check.deployment.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.check.deployment.nodeSelector | trim | nindent 6 }}
    {{- end }}
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-check-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-service-role
subjects:
  - kind: ServiceAccount
    name: deployment-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-service-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: {{ .Release.Namespace }}
{{- end }}

