---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kuberhealthy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/owner: sditeam

