---
apiVersion: v1
name: "kuberhealthy"
version: 2.1.2
appVersion: 2.1.2
home: https://comcast.github.io/kuberhealthy/
description: A Helm chart for Kuberhealthy, an operator for synthetic test and monitoring.
type: application
keywords:
- kuberhealthy
- kubernetes
- operator
- monitoring
- synthetic
- testing
- comcast
- health
- prometheus
sources:
- https://github.com/Comcast/kuberhealthy
- https://github.com/helm/charts/tree/master/stable/kuberhealthy
icon: https://raw.githubusercontent.com/Comcast/kuberhealthy/master/images/logo-square.png
